export const NEWS_REQUEST = 'NEWS_REQUEST'
export const NEWS_SUCCESS = 'NEWS_SUCCESS'
export const NEWS_FAIL = 'NEWS_FAIL'

export const POPULAR_NEWS_REQUEST = 'POPULAR_NEWS_REQUEST'
export const POPULAR_NEWS_SUCCESS = 'POPULAR_NEWS_SUCCESS'
export const POPULAR_NEWS_FAIL = 'POPULAR_NEWS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'